### ISSUE TITLE
doesnt load at all.

### ISSUE THREAD

**Issue by imhereforthedoommods** [inkoalawetrust/Smart-Marines#2]
Yeah, when I try to open it with GZDoom or GZDoom/ZDoom builder, they just go POOF! right back into regular ZDoom marines, unless they have a default gray skin.

**Comment by inkoalawetrust** [comment]
Are you sure you are loading them in as a resource ? Try also adding the gzdoom.pk3 file as a resource in UDB, and also make sure to exclude it from testing parameters. ZScript actors require you to have the engine archive loaded to properly load in.

**Comment by inkoalawetrust** [comment]
Since I have not received any update on this, I'm just going to close the issue.
