### ISSUE TITLE
eday vanilla

### ISSUE THREAD

**Issue by ak1dd** [inkoalawetrust/Smart-Marines#3]
First, thanks for this... very cool.   Doom AI in general has never been satisfactorily addressed IMO and this is fun.

I can get the Project Brutality version to run with only some maps/mods.   I often get this:

```
Brightmap 'brightmaps/LIT05.png' not found in texture 'LIT05'
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
DistX in slider decal Drops is unsupported
DistX in slider decal Drops is unsupported
M_Init: Init menus.
Script error, "Smart.Marines.Project.Brutality.pk3:mapinfo" line 5:
Unknown actor class VanillaRifle

Execution could not continue.

1 unknown actor classes found
```

Although likely a conflicting mod,  I thought I'd test Smart-Marines Project Brutality with Eday Vanilla 2019.   There are a few maps here that start with many marine NPCs (like 12 at the map start).    Try map 16.

I get the same error on other maps too...  VanillaRifle?

Using the latest Project Brutality, Smart Marines and latest GZDoom.

**Comment by inkoalawetrust** [comment]
That's the rifle the normal marines drop, I stopped the code for it from being loaded. To have the marines instead drop the DMR. But apparently GZDoom works in mysterious ways, and didn't complain about leftover references to the marines' normal rifle, until after I published the PB version of the mod.

I've fixed it on the latest 1.0.2 release for PB.
