### ISSUE TITLE
Smart Marine 1.3.1 Grenade Spam 

### ISSUE THREAD

**Issue by LocutusofBorg77** [inkoalawetrust/Smart-Marines#4]
![screenshot 1](https://user-images.githubusercontent.com/105587626/174341067-094763b7-7121-4abd-b074-cd80d4cd1820.jpg)
Gzdoom 4.8.0
Smart Marine 1.3.1

When playing Ultimate Doom without any add-ons even on the lowest Difficulty, if they see only one enemy they spam grenades.
It seems its more excessive on higher difficulties especially Nightmare. 

Zdoom Discord: 
LocutusofBorg#0852

**Comment by inkoalawetrust** [comment]
Well after some testing. I didn't notice any issues with the marines throwing too many grenades. At most they throw a grenade every 10-20 seconds.

**Comment by LocutusofBorg77** [comment]
I tried multiple times and the Marines throw multiple grenades in seconds even on single enemies

**Comment by inkoalawetrust** [comment]
Well in that case, open up the mod, go to the ZScript.zsc file, then go to line 889 and add this line of code in the exact position as the screenshot.

![image](https://user-images.githubusercontent.com/56005600/174386892-6f705c39-7723-467b-a85c-c0a47020bc7e.png)

`GrenadeDelay = 40; //Don't throw a grenade again until at least a second has passed.`

**Comment by inkoalawetrust** [comment]
Alright, you told me on Discord that adding a delay after every throw worked, so I'm closing this now.
