### ISSUE TITLE
Smart Marines 1.3.1 freeze with Brutal Doom

### ISSUE THREAD

**Issue by LocutusofBorg77** [inkoalawetrust/Smart-Marines#5]
![screenshot 1](https://user-images.githubusercontent.com/105587626/174341067-094763b7-7121-4abd-b074-cd80d4cd1820.jpg)
Gzdoom 4.8.0
Smart Marine 1.3.1
Any Brutal doom based add-on
(e.g. Brutal Doom Platinum 3.0 or Brutal Doom Community Expansion 21.12.0 and 21.12.1 Dev)

After approx. 5-10 Minutes Gzdoom freezes completely and can only be closed via Locking the Computer and then it says Gzdoom stopped working.

Zdoom Discord: 
LocutusofBorg#0852

**Comment by inkoalawetrust** [comment]
Well, I tried out playing BD Platinum with the marines for about half an hour. And didn't have the game freeze at all on my end. So I don't think anything in BD is conflicting with the marines. But if you do have GZDoom or another program totally freeze again, I'd suggest downloading and using [SuperF4](https://stefansundin.github.io/superf4/).

**Comment by LocutusofBorg77** [comment]
Thanks I'll do that.
